"""button table

Revision ID: f4ecd3735aaf
Revises: 
Create Date: 2021-03-19 19:04:24.519340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4ecd3735aaf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('button',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('button_name', sa.String(length=64), nullable=True),
    sa.Column('button_web_id', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_button_button_name'), 'button', ['button_name'], unique=True)
    op.create_index(op.f('ix_button_button_web_id'), 'button', ['button_web_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_button_button_web_id'), table_name='button')
    op.drop_index(op.f('ix_button_button_name'), table_name='button')
    op.drop_table('button')
    # ### end Alembic commands ###
